version: 2
jobs:
  build:
    working_directory: ~/tiles
    docker:
      - image: circleci/node:12.10.0
    steps:
      # Checkout and update npm.
      - checkout
      - run:
          name: npm-update
          command: 'sudo npm install -g npm@latest'
      # Restore cached dependencies.
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      # Cache dependencies.
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # Run tests
      - run:
          name: test
          command: npm test
      # Lint
      - run:
          name: lint
          command: npm run lint
      # Build
      - run:
          name: build-prod
          command: npm run build

