version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  verify:
    executor:
      name: node/default
    steps:
      - checkout
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn test
      - run: yarn lint
workflows:
  integration:
    jobs:
      - verify
